### ISSUE TITLE
social card can refresh its value only once

### ISSUE THREAD

**Issue by cometkim** [edykim/edykim.com#35]
I tried to use the social card plugin with sharp:

![Peek 2020-01-27 23-19](https://user-images.githubusercontent.com/9696352/73182407-5f4e8700-415c-11ea-8337-24ebc9bf1efa.gif)

When changing the value of the source node, the social card is re-generated properly for the first time, but not for next.

sorry, I'm not sure why this happened at this moment. will investigate later

**Comment by edykim** [comment]
I'm closing this issue cause the website does not use Gatsby anymore. (What a good old day ha)

**Comment by cometkim** [comment]
> I'm closing this issue cause the website does not use Gatsby anymore. (What a good old day ha)

Nostalgic!

Fyi, the best solution for the content-aware og generation today IMO is satori with HTMLRewirter

E.g. https://developers.cloudflare.com/pages/functions/plugins/vercel-og/
