### ISSUE TITLE
RSS 피드 사용 시 한국어 글 주소가 제대로 표시되지 않습니다

### ISSUE THREAD

**Issue by znagadeon** [edykim/edykim.com#59]
안녕하세요. 블로그를 RSS 리더로 구독중인데 매번 글이 not found로 표시되더라구요.

확인해보니 RSS로 오는 url은
<https://edykim.com/post/lenovo-thinkpad-x1-6gen-display-replacement/>
인데, 실제로 글이 있는 위치는
<https://edykim.com/ko/post/lenovo-thinkpad-x1-6gen-display-replacement/>
여기입니다.

**Comment by edykim** [comment]
지금까지 전혀 모르고 있었네요 ㅠㅠ 해당 문제를 수정했습니다. 알려주셔서 감사합니다 😇
