### ISSUE TITLE
RSS feed를 제공하실 계획이 있으신가요?

### ISSUE THREAD

**Issue by saengmotmi** [edykim/edykim.com#86]
글이 좋아서 rss로 구독해서 읽고 싶은데 블로그에 관련 세팅이 없으신거 같아서 혹시 추가하실 계획이 있으신지 여쭙습니다!

**Comment by edykim** [comment]
문의 감사드립니다. 현재 아래 주소로 피드가 제공되고 있습니다.

- 전체 블로그 포스트: https://edykim.com/ko/feed.xml
- 개발 관련 포스트: https://edykim.com/ko/dev-life/feed.xml

**Comment by saengmotmi** [comment]
오 제가 못찾았었군요 ㅎㅎ 답변 감사합니다!
