### ISSUE TITLE
Bug: broken `feed.xml` link

### ISSUE THREAD

**Issue by ysm0622** [edykim/edykim.com#9]
![image](https://user-images.githubusercontent.com/18487241/51069898-70287980-167b-11e9-9f56-a53ab93009be.png)

![image](https://user-images.githubusercontent.com/18487241/51069909-a0701800-167b-11e9-8fb5-8ef6ff14f3d4.png)

rss feed의 `link` 태그와 `guid` 태그가 실제 포스트의 url과 달라서

rss feed의 `link` tag : `https://edykim.com/ko/posts/2019-01-11-translate-talk/`

실제 URL : `https://edykim.com/ko/post/talk-translate-what-i-want/`

rss reader를 타고 들어올때 링크가 깨지는 현상이 있습니다.

![image](https://user-images.githubusercontent.com/18487241/51069931-ea58fe00-167b-11e9-9625-328903257958.png)

**Comment by edykim** [comment]
수정 반영했습니다. 알려주셔서 감사드립니다!
